### ISSUE TITLE
Can't logout - I automatically get logged in again

### ISSUE THREAD

**Issue by thomasdarimont** [osiam/addon-administration#90]
If I click on the logout button in the addon-administration UI I end up at the same page (user listing) after a few (internal) redirects.

I would expect to be redirected to an "logged-out" page and that I have to login again when I want to access the user / group listing the next time.

**Comment by tkrille** [comment]
Hi @thomasdarimont,

this behavior is already known and addressed in issue #64. But here's some brief explanation what's going on:

When click the logout link the apps somehow forgets your access token, making you not logged in. After a redirect it notices that you're not logged in and redirects again to the auth-server to start an OAuth authorization code grant. As you still have a valid session with the auth-server, you won't be requested to log in again. As the addon-administration has implicit approval set (because it's a secure, trusted system app), you won't be requested to approve. So the last step of the grant kicks in, which is redirecting to the app with an auth code and effectively making you being logged in again.

The main problem here is, that OSIAM does not really support the concept of a "logout", which is not so easy to describe in different distributed environments anyways. I think, there are some ideas about a global logout (destroying all access tokens and sessions on the auth-server) and a client based logout (destroying all access tokens issued by a single client and flagging the client in a way, so that the next time you start an auth code grant with this client, you'll be forced to login again). But this is all in very early stage.

So, I'm closing this as duplicate, if everyone's ok with that.
